import Foundation

/// `.xcstrings` 이전 형식. 아직 String Catalog 로 못 옮긴 프로젝트를 위한 것이다.
///
/// 복수형이 `.stringsdict` 로 따로 나가는 게 이 형식의 특징이자 불편한 점이다. String
/// Catalog 는 둘을 한 파일에 담지만, 이쪽은 로케일마다 `.strings` 와 `.stringsdict` 두
/// 파일로 갈린다.
public enum LegacyOutput {

    // MARK: - .strings

    /// 로케일 하나의 `Localizable.strings`.
    ///
    /// 키 순으로 정렬한다 — 시트 순서를 따라가면 행 하나 옮길 때마다 파일 전체가 diff 에 뜬다.
    public static func strings(
        for locale: String, entries: [LocalizationEntry], comments: Bool = true
    ) -> String {
        var out = "// Generated by stringsmith. Do not edit.\n"

        for entry in entries.sorted(by: { $0.key < $1.key }) {
            guard let value = entry.values[locale], !value.isEmpty else { continue }
            if comments, let comment = XCStringsDocument.comment(for: entry) {
                out += "\n/* \(comment.replacingOccurrences(of: "*/", with: "* /")) */\n"
            } else {
                out += "\n"
            }
            out += "\"\(escape(entry.key))\" = \"\(escape(value))\";\n"
        }
        return out
    }

    /// `.strings` 문법에서 뜻이 있는 문자들.
    static func escape(_ text: String) -> String {
        var out = ""
        for character in text {
            switch character {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            case "\n": out += "\\n"
            case "\t": out += "\\t"
            case "\r": out += "\\r"
            default: out.append(character)
            }
        }
        return out
    }

    // MARK: - .stringsdict

    /// 로케일 하나의 `Localizable.stringsdict`.
    ///
    /// 묶음이 없으면 `nil` — 빈 plist 를 남겨 두면 Xcode 가 경고를 낸다.
    public static func stringsdict(
        for locale: String, groups: [PluralGroup]
    ) -> String? {
        let usable = groups.filter { group in
            group.variants.contains { !($0.value.values[locale] ?? "").isEmpty }
        }
        guard !usable.isEmpty else { return nil }

        var out = """
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" \
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>

            """

        for group in usable.sorted(by: { $0.key < $1.key }) {
            out += "\t<key>\(xml(group.key))</key>\n"
            out += "\t<dict>\n"
            out += "\t\t<key>NSStringLocalizedFormatKey</key>\n"
            out += "\t\t<string>%#@count@</string>\n"
            out += "\t\t<key>count</key>\n"
            out += "\t\t<dict>\n"
            out += "\t\t\t<key>NSStringFormatSpecTypeKey</key>\n"
            out += "\t\t\t<string>NSStringPluralRuleType</string>\n"
            // 복수형은 셀 수 있는 것에 붙는다. 다른 변수는 문자열로 두지만 이 자리만은
            // 정수여야 iOS 가 어느 범주인지 고를 수 있다.
            out += "\t\t\t<key>NSStringFormatValueTypeKey</key>\n"
            out += "\t\t\t<string>d</string>\n"

            for category in PluralCategory.allCases {
                guard let entry = group.variants[category],
                    let value = entry.values[locale], !value.isEmpty
                else { continue }
                out += "\t\t\t<key>\(category.rawValue)</key>\n"
                out += "\t\t\t<string>\(xml(value))</string>\n"
            }

            out += "\t\t</dict>\n"
            out += "\t</dict>\n"
        }

        out += "</dict>\n</plist>\n"
        return out
    }

    /// XML 에서 뜻이 있는 문자들. 값에 `<b>` 같은 마크업이 들어오는 일이 실제로 있다.
    static func xml(_ text: String) -> String {
        var out = ""
        for character in text {
            switch character {
            case "&": out += "&amp;"
            case "<": out += "&lt;"
            case ">": out += "&gt;"
            default: out.append(character)
            }
        }
        return out
    }
}
