// Generated by stringsmith. DO NOT EDIT.
//
// 이 파일은 스프레드시트에서 생성됩니다. 직접 고치면 다음 실행에 덮어써집니다.

import Foundation

// swiftlint:disable all
// swift-format-ignore-file

public enum L10n {

    public enum App {

        /// 공통 — 부제
        ///
        /// ko: "시트 한 장에서 여기까지"
        public static var subtitle: String {
            L10n.lookUp("app.subtitle")
        }

        /// 공통 — 앱 이름
        ///
        /// ko: "스트링스미스 데모"
        public static var title: String {
            L10n.lookUp("app.title")
        }
    }

    public enum Cart {

        /// 장바구니 — 할인 배너. 퍼센트가 리터럴이다
        ///
        /// ko: "%@ 50%% 할인"
        public static func discount(_ arg1: String) -> String {
            L10n.lookUp("cart.discount", arg1)
        }

        /// 장바구니 — 비었을 때
        ///
        /// ko: "장바구니가 비었습니다"
        public static var empty: String {
            L10n.lookUp("cart.empty")
        }

        /// 장바구니 — 인사말. 이름이 들어간다
        ///
        /// ko: "%@님의 장바구니"
        public static func greeting(_ arg1: String) -> String {
            L10n.lookUp("cart.greeting", arg1)
        }

        /// 장바구니 — 상품 여러 개
        ///
        /// ko: "상품 %d개"
        public static func items(_ arg1: Int) -> String {
            L10n.lookUp("cart.items", arg1)
        }

        /// 장바구니 — 화면 제목
        ///
        /// ko: "장바구니"
        public static var title: String {
            L10n.lookUp("cart.title")
        }
    }

    public enum Common {

        /// 공통 — 취소
        ///
        /// ko: "취소"
        public static var cancel: String {
            L10n.lookUp("common.cancel")
        }

        /// 공통 — 확인
        ///
        /// ko: "확인"
        public static var ok: String {
            L10n.lookUp("common.ok")
        }
    }
}

extension L10n {
    private static let bundle: Bundle = Bundle.module

    fileprivate static func lookUp(_ key: String, _ arguments: CVarArg...) -> String {
        let format = NSLocalizedString(
            key, tableName: "Localizable", bundle: bundle, value: key, comment: ""
        )
        guard !arguments.isEmpty else { return format }
        return String(format: format, locale: .current, arguments: arguments)
    }
}
